import prompts from 'prompts'
import { existsSync, readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { execSync } from 'node:child_process'

function checkCommand(cmd: string): boolean {
  try {
    execSync(`which ${cmd}`, { stdio: 'ignore' })
    return true
  } catch {
    return false
  }
}

function readEnvFile(cwd: string): Record<string, string> {
  const envPath = join(cwd, '.env.local')
  if (!existsSync(envPath)) return {}
  const content = readFileSync(envPath, 'utf-8')
  const vars: Record<string, string> = {}
  for (const line of content.split('\n')) {
    const match = line.match(/^([A-Z_]+)=(.+)$/)
    if (match) vars[match[1]] = match[2]
  }
  return vars
}

async function main() {
  const cwd = resolve(process.cwd())

  console.error()
  console.error('  feedback-chat agent deployment script generator')
  console.error('  ────────────────────────────────────────────────')
  console.error()

  // Check prerequisites
  const hasRailway = checkCommand('railway')
  const hasGh = checkCommand('gh')

  if (!hasRailway) {
    console.error('  ✗ Railway CLI not found. Install: npm install -g @railway/cli')
    process.exit(1)
  }
  if (!hasGh) {
    console.error('  ✗ GitHub CLI not found. Install: https://cli.github.com/')
    process.exit(1)
  }

  // Read .env.local
  const envVars = readEnvFile(cwd)
  const githubToken = envVars['GITHUB_TOKEN'] || ''
  const githubRepo = envVars['GITHUB_REPO'] || ''
  const anthropicKey = envVars['ANTHROPIC_API_KEY'] || ''

  if (!githubToken || !githubRepo) {
    console.error('  ✗ GITHUB_TOKEN and GITHUB_REPO must be set in .env.local')
    console.error('  Run `npx feedback-chat init` first with the +GitHub or +Pipeline tier.')
    process.exit(1)
  }

  // Auth choice
  const { authMethod } = await prompts({
    type: 'select',
    name: 'authMethod',
    message: 'Claude authentication for the agent',
    choices: [
      {
        title: 'Claude Max subscription ($0/run)',
        description: 'Uses OAuth credentials from your local keychain',
        value: 'max',
      },
      {
        title: 'API key (pay per token)',
        description: 'Uses ANTHROPIC_API_KEY from .env.local',
        value: 'api',
      },
    ],
  })

  if (!authMethod) {
    console.error('  Cancelled.')
    process.exit(0)
  }

  let credentialsJson = ''
  if (authMethod === 'max') {
    console.error()
    console.error('  To get your Claude credentials, run:')
    console.error('    security find-generic-password -s "Claude Code-credentials" -a "$USER" -w')
    console.error()
    console.error('  Copy the JSON output (the claudeAiOauth portion).')
    console.error()

    const { creds } = await prompts({
      type: 'text',
      name: 'creds',
      message: 'Paste your Claude credentials JSON (or press Enter to include a placeholder)',
    })
    credentialsJson = creds || '${CLAUDE_CREDENTIALS_JSON}'
  }

  // Generate webhook secret
  const webhookSecret = '$(openssl rand -hex 32)'

  // Build the script
  const envLocalPath = join(cwd, '.env.local')

  const authLine = authMethod === 'max'
    ? `\n  CLAUDE_CREDENTIALS_JSON='${credentialsJson.replace(/'/g, "'\\''")}'`
    : anthropicKey
      ? `\n  ANTHROPIC_API_KEY="${anthropicKey}"`
      : ''

  const script = `#!/usr/bin/env bash
set -euo pipefail

# ── feedback-chat agent deployment script ──
# Generated by: npx feedback-chat deploy-agent
# Review this script before running it.

echo "==> Cloning feedback-chat agent..."
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT
git clone --depth 1 https://github.com/NikitaDmitrieff/feedback-chat "$TMPDIR/feedback-chat"
cd "$TMPDIR/feedback-chat/packages/agent"

echo "==> Creating Railway project..."
railway init

echo "==> First deploy (creates the service)..."
DEPLOY_OUTPUT=$(railway up --detach 2>&1)
echo "$DEPLOY_OUTPUT"

echo "==> Waiting for service to register..."
sleep 5

echo "==> Finding and linking service..."
SERVICE_NAME=$(railway service status --all 2>&1 | grep -oE '^[a-z][-a-z0-9]*' | head -1)
if [ -z "$SERVICE_NAME" ]; then
  echo "✗ Could not detect service name. Run 'railway service status --all' manually."
  exit 1
fi
echo "   Linking service: $SERVICE_NAME"
railway service link "$SERVICE_NAME"

echo "==> Setting environment variables..."
WEBHOOK_SECRET=${webhookSecret}
railway variables set \\
  GITHUB_TOKEN="${githubToken}" \\
  GITHUB_REPO="${githubRepo}" \\
  WEBHOOK_SECRET="$WEBHOOK_SECRET"${authLine ? ` \\${authLine}` : ''}

echo "==> Getting public domain..."
DOMAIN_OUTPUT=$(railway domain 2>&1)
AGENT_URL=$(echo "$DOMAIN_OUTPUT" | grep -oE 'https://[^ ]+')
if [ -z "$AGENT_URL" ]; then
  echo "✗ Could not extract domain URL. Output was:"
  echo "$DOMAIN_OUTPUT"
  exit 1
fi
echo "   Agent URL: $AGENT_URL"

echo "==> Setting up GitHub webhook..."
REPO_OWNER=$(echo "${githubRepo}" | cut -d/ -f1)
REPO_NAME=$(echo "${githubRepo}" | cut -d/ -f2)
gh api "repos/$REPO_OWNER/$REPO_NAME/hooks" \\
  -f name=web -F active=true \\
  -f "config[url]=$AGENT_URL/webhook/github" \\
  -f "config[content_type]=json" \\
  -f "config[secret]=$WEBHOOK_SECRET" \\
  -f 'events[]=issues'

echo "==> Updating consumer .env.local..."
echo "AGENT_URL=$AGENT_URL" >> "${envLocalPath}"

echo ""
echo "==> Done! Summary:"
echo "   Agent URL:      $AGENT_URL"
echo "   Webhook:        $AGENT_URL/webhook/github"
echo "   Webhook secret: $WEBHOOK_SECRET"
echo ""
echo "   Next steps:"
echo "   1. Wait for Railway deploy to finish"
echo "   2. Verify: curl $AGENT_URL/health"
echo "   3. Test by submitting feedback through the widget"
`

  // Output the script to stdout
  process.stdout.write(script)

  console.error()
  console.error('  Script generated! To run it:')
  console.error('    npx feedback-chat deploy-agent | bash')
  console.error('  Or save and review first:')
  console.error('    npx feedback-chat deploy-agent > deploy.sh && chmod +x deploy.sh && cat deploy.sh')
  console.error()
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
