import { execFileSync } from 'node:child_process'
import { mkdtempSync, rmSync, existsSync, readFileSync } from 'node:fs'
import { tmpdir, homedir } from 'node:os'
import { join } from 'node:path'
import type { SupabaseClient } from '@supabase/supabase-js'
import { getInstallationToken } from './github-app.js'
import { initCredentials, ensureValidToken } from './oauth.js'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnySupabaseClient = SupabaseClient<any, any, any>

export type SetupJobInput = {
  jobId: string
  projectId: string
  githubRepo: string
  installationId: number
  supabase: AnySupabaseClient
}

const FEEDBACK_LABELS = [
  { name: 'feedback-bot', color: '0E8A16', description: 'Created by feedback widget' },
  { name: 'auto-implement', color: '1D76DB', description: 'Agent should implement this' },
  { name: 'in-progress', color: 'FBCA04', description: 'Agent is working on this' },
  { name: 'agent-failed', color: 'D93F0B', description: 'Agent build/lint failed' },
  { name: 'preview-pending', color: 'C5DEF5', description: 'PR ready, preview deploying' },
  { name: 'rejected', color: 'E4E669', description: 'User rejected changes' },
]

function updateStatus(supabase: AnySupabaseClient, projectId: string, status: string, extra?: Record<string, string | null>) {
  return supabase
    .from('projects')
    .update({ setup_status: status, ...extra })
    .eq('id', projectId)
}

function run(cmd: string, args: string[], cwd: string, env?: Record<string, string | undefined>): string {
  return execFileSync(cmd, args, {
    cwd,
    env: env ? { ...process.env, ...env } : process.env,
    encoding: 'utf-8',
    timeout: 300_000,
    maxBuffer: 10 * 1024 * 1024,
  })
}

export async function runSetupJob(input: SetupJobInput): Promise<void> {
  const { jobId, projectId, githubRepo, installationId, supabase } = input
  const [owner, repo] = githubRepo.split('/')
  let workDir = ''

  try {
    // 1. Clone
    await updateStatus(supabase, projectId, 'cloning')
    console.log(`[setup:${jobId}] Cloning ${githubRepo}...`)

    const token = await getInstallationToken(installationId)
    workDir = mkdtempSync(join(tmpdir(), 'setup-'))
    run('git', ['clone', '--depth', '1', `https://x-access-token:${token}@github.com/${owner}/${repo}.git`, '.'], workDir)

    // 2. Generate with Claude Code
    await updateStatus(supabase, projectId, 'generating')
    console.log(`[setup:${jobId}] Running Claude Code...`)

    // Build Claude env
    const claudeEnv: Record<string, string | undefined> = { ...process.env }

    // Check for project-level credentials
    const { data: cred } = await supabase
      .from('credentials')
      .select('type, encrypted_value')
      .eq('project_id', projectId)
      .limit(1)
      .single()

    if (cred) {
      if (cred.type === 'claude_oauth') {
        // Set CLAUDE_CREDENTIALS_JSON so initCredentials() writes the file
        process.env.CLAUDE_CREDENTIALS_JSON = cred.encrypted_value
        initCredentials()
        await ensureValidToken()
        const credsPath = join(homedir(), '.claude', '.credentials.json')
        if (existsSync(credsPath)) {
          const credsData = JSON.parse(readFileSync(credsPath, 'utf-8'))
          claudeEnv.CLAUDE_CODE_OAUTH_TOKEN = credsData?.claudeAiOauth?.accessToken
          delete claudeEnv.ANTHROPIC_API_KEY
        }
      } else {
        claudeEnv.ANTHROPIC_API_KEY = cred.encrypted_value
      }
    }

    claudeEnv.CI = 'true'

    const setupPrompt = buildSetupPrompt(githubRepo)
    run('claude', ['--dangerously-skip-permissions', '-p', setupPrompt], workDir, claudeEnv)

    // 3. Commit + push
    await updateStatus(supabase, projectId, 'committing')
    console.log(`[setup:${jobId}] Pushing changes...`)

    run('git', ['checkout', '-b', 'feedback-chat/setup'], workDir)
    run('git', ['add', '-A'], workDir)

    // Check if there are changes to commit
    try {
      run('git', ['diff', '--cached', '--quiet'], workDir)
      // If no error, there are no changes — Claude didn't modify anything
      throw new Error('Claude Code did not generate any files. The setup prompt may need adjustment.')
    } catch (e) {
      // git diff --cached --quiet exits 1 when there ARE changes — that's what we want
      if (e instanceof Error && e.message.includes('did not generate')) throw e
    }

    run('git', ['commit', '-m', 'feat: add feedback-chat widget\n\nAuto-generated by Feedback Chat dashboard.'], workDir)

    // Get fresh token for push (original may have been used a while ago)
    const pushToken = await getInstallationToken(installationId)
    run('git', ['remote', 'set-url', 'origin', `https://x-access-token:${pushToken}@github.com/${owner}/${repo}.git`], workDir)
    run('git', ['push', '-u', 'origin', 'feedback-chat/setup', '--force'], workDir)

    // 4. Create PR via GitHub API
    console.log(`[setup:${jobId}] Creating PR...`)
    const prResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${pushToken}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      body: JSON.stringify({
        title: 'Add feedback-chat widget',
        head: 'feedback-chat/setup',
        base: 'main',
        body: buildPrBody(githubRepo),
      }),
    })

    if (!prResponse.ok) {
      const text = await prResponse.text()
      // 422 = PR already exists (branch already has a PR)
      if (prResponse.status !== 422) {
        throw new Error(`Failed to create PR: ${prResponse.status} ${text}`)
      }
    }

    const prData = await prResponse.json()
    const prUrl = prData.html_url ?? null

    // 5. Create labels (idempotent)
    console.log(`[setup:${jobId}] Creating labels...`)
    for (const label of FEEDBACK_LABELS) {
      await fetch(`https://api.github.com/repos/${owner}/${repo}/labels`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${pushToken}`,
          Accept: 'application/vnd.github+json',
        },
        body: JSON.stringify(label),
      }).catch(() => {}) // Ignore errors (label may already exist)
    }

    // 6. Done
    await updateStatus(supabase, projectId, 'pr_created', { setup_pr_url: prUrl })
    console.log(`[setup:${jobId}] Done! PR: ${prUrl}`)

  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    console.error(`[setup:${jobId}] Failed: ${message}`)
    await updateStatus(supabase, projectId, 'failed', { setup_error: message })
    throw err
  } finally {
    if (workDir) rmSync(workDir, { recursive: true, force: true })
  }
}

function buildSetupPrompt(githubRepo: string): string {
  return `You are setting up the @nikitadmitrieff/feedback-chat widget in this Next.js project.

Do the following steps in order:

1. Check if this is a Next.js project. Find the app directory (usually app/ or src/app/).
2. Install the package and peer dependencies:
   npm install @nikitadmitrieff/feedback-chat @assistant-ui/react @assistant-ui/react-ai-sdk @assistant-ui/react-markdown ai @ai-sdk/anthropic
3. Find the main CSS file (usually globals.css or app/globals.css).
   - If using Tailwind v4 (has @import "tailwindcss"), add AFTER that import:
     @source "../node_modules/@nikitadmitrieff/feedback-chat/dist/**/*.js";
   - If using Tailwind v3, add the path to the content array in tailwind.config.
4. Create the chat API route at {appDir}/api/feedback/chat/route.ts:
   import { createFeedbackHandler } from '@nikitadmitrieff/feedback-chat/server'
   const handler = createFeedbackHandler({
     password: process.env.FEEDBACK_PASSWORD!,
     github: {
       token: process.env.GITHUB_TOKEN!,
       repo: '${githubRepo}',
     },
   })
   export const POST = handler.POST
5. Create the status API route at {appDir}/api/feedback/status/route.ts:
   import { createStatusHandler } from '@nikitadmitrieff/feedback-chat/server'
   const handler = createStatusHandler({
     password: process.env.FEEDBACK_PASSWORD!,
     github: {
       token: process.env.GITHUB_TOKEN!,
       repo: '${githubRepo}',
     },
   })
   export const { GET, POST } = handler
6. Create a client component at components/FeedbackButton.tsx:
   'use client'
   import { useState } from 'react'
   import { FeedbackPanel } from '@nikitadmitrieff/feedback-chat'
   import '@nikitadmitrieff/feedback-chat/styles.css'
   export function FeedbackButton() {
     const [open, setOpen] = useState(false)
     return <FeedbackPanel isOpen={open} onToggle={() => setOpen(!open)} />
   }
7. Add <FeedbackButton /> to the root layout inside the <body> tag.
   Import it: import { FeedbackButton } from '@/components/FeedbackButton'
8. Create a .env.local.example file listing the required env vars:
   ANTHROPIC_API_KEY=sk-ant-...
   FEEDBACK_PASSWORD=easy
   GITHUB_TOKEN=ghp_...
   GITHUB_REPO=${githubRepo}

IMPORTANT:
- Do NOT install React — it is already a dependency.
- Do NOT modify existing components beyond adding the FeedbackButton import to the layout.
- Do NOT commit anything — just make the file changes.
- If you cannot find the app directory, look for a next.config file to confirm it is a Next.js project.`
}

function buildPrBody(githubRepo: string): string {
  return `## Add feedback-chat widget

This PR was auto-generated by the [Feedback Chat](https://github.com/NikitaDmitrieff/feedback-chat) dashboard.

### What's included
- \`/api/feedback/chat\` — AI conversation endpoint
- \`/api/feedback/status\` — Pipeline status endpoint
- \`<FeedbackButton />\` — Client component wrapper
- Tailwind configuration for widget styles
- \`.env.local.example\` — Required environment variables

### After merging

Add these to your \`.env.local\`:
\`\`\`
ANTHROPIC_API_KEY=sk-ant-...
FEEDBACK_PASSWORD=easy
\`\`\`

Then restart your dev server: \`npm run dev\`

The feedback password defaults to \`easy\` — change it before going to production.

---
*Auto-generated by [Feedback Chat](https://github.com/NikitaDmitrieff/feedback-chat) dashboard*`
}
